resolver: lts-16.3
extra-deps:
  - binaryen-0.0.1.1
  - url: https://github.com/tweag/inline-js/archive/55f6530683aeda8f7235996197ded3509e2ed09f.tar.gz
    subdirs:
      - inline-js-core
packages:
  - asterius
  - ghc-toolkit
  - wasm-toolkit


system-ghc: false

compiler: ghc-8.8.3

extra-lib-dirs:
- /nix/store/8mhxy2gmi2hgh2p31j343mwrssyng0fb-binaryen-93/lib
- /nix/store/1jl5kvjxhg1dxj9k1c0h4mpviqqcn3bi-ncurses-6.2/lib

# ghc-variant: asterius

setup-info:
  ghc:
    linux64-custom-asterius-tinfo6:
      8.8.3:
        url: https://asterius.s3-us-west-2.amazonaws.com/ghc-8.8.3-linux64-custom-asterius-tinfo6.200517.tar.xz
        content-length: 151370468
        sha256: 5119077a912427cad99554ab9b531305ce539b5e1b541c909bb09a68fd7ef8ae
    linux64-custom-asterius:
      8.8.3:
        url: https://asterius.s3-us-west-2.amazonaws.com/ghc-8.8.3-linux64-custom-asterius.200517.tar.xz
        content-length: 148343252
        sha256: f078fa1f29b0a4deb23bba12915b22f86927bf1062e43bc4b31559885f24676e
    linux64-custom-asterius-musl:
      8.8.3:
        url: https://asterius.s3-us-west-2.amazonaws.com/ghc-8.8.3-linux64-custom-asterius-musl.200517.tar.xz
        content-length: 165664120
        sha256: 86aa81bea2245efba05de23c73dd70ded06c84d61481c9e0a680d423cd3400be
    macosx-custom-asterius:
      8.8.3:
        url: https://asterius.s3-us-west-2.amazonaws.com/ghc-8.8.3-macosx-custom-asterius.200517.tar.xz
        content-length: 159032416
        sha256: 4fdde14b04392541abe5ad441ef98a4c924c6b0195f6f35f0ec79e04798f4f58
